#!/sbin/runscript
# Copyright 2002 Frauenhofer Gesellschaft FOKUS, Germany.
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header$

depend() {
	need net
}

start() {
	ebegin "Starting OpenMarinkaRodeo"
	start-stop-daemon --start --quiet --pidfile /var/run/openMarinkaRodeo.pid \
		--exec /usr/sbin/openMarinkaRodeo -- -P /var/run/openMarinkaRodeo.pid
	eend $?
}

stop() {
	ebegin "Stopping OpenMarinkaRodeo"
	start-stop-daemon --stop --quiet --pidfile /var/run/openMarinkaRodeo.pid
	eend $?
}

