.TH openMarinkaRodeo.cfg 5 08.06.2006 openMarinkaRodeo "Open SIP Server" 
.\" Process with
.\" groff -man -Tascii openMarinkaRodeo.cfg.5 
.\"
.SH NAME
openMarinkaRodeo.cfg \- openMarinkaRodeo configuration file
.SH SYNOPSIS
.I /etc/openMarinkaRodeo/openMarinkaRodeo.cfg
.SH DESCRIPTION
.B openMarinkaRodeo
reads the configuration data from
.I /etc/openMarinkaRodeo/openMarinkaRodeo.cfg
(or the file specified with
.B \-f
on the command line).
The file contains global configuration parameters, module loading commands and the script that will be executed for each received request. Lines starting with
.B #
or enclosed in
.B /* ... */
are interpreted as comments.
.PP
This manual page is incomplete. For further information please read the
.I openMarinkaRodeo documentation (https://openMarinkaRodeo.org/).

.SH FILES
.PD 0
.I /etc/openMarinkaRodeo/openMarinkaRodeo.cfg
.br

.SH AUTHORS

see 
.B /usr/share/doc/openMarinkaRodeo/AUTHORS

.SH SEE ALSO
.BR openMarinkaRodeo(8)
.PP
Full documentation on openMarinkaRodeo is available at
.I https://openMarinkaRodeo.org/.
.PP
Mailing lists:
.nf 
users@lists.openMarinkaRodeo.org - openMarinkaRodeo user community
.nf 
devel@lists.openMarinkaRodeo.org - openMarinkaRodeo development, new features and unstable version

