.\" $Id$
.TH Marina.Rodeo.cfg 5 08.06.2006 Marina.Rodeo "Open SIP Server" 
.\" Process with
.\" groff -man -Tascii Marina.Rodeo.cfg.5 
.\"
.SH NAME
Marina.Rodeo.cfg \- Marina.Rodeo configuration file
.SH SYNOPSIS
.I /etc/Marina.Rodeo/Marina.Rodeo.cfg
.SH DESCRIPTION
.B Marina.Rodeo
reads the configuration data from
.I /etc/Marina.Rodeo/Marina.Rodeo.cfg
(or the file specified with
.B \-f
on the command line).
The file contains global configuration parameters, module loading commands and the script that will be executed for each received request. Lines starting with
.B #
or enclosed in
.B /* ... */
are interpreted as comments.
.PP
This manual page is incomplete. For further information please read the
.I Marina.Rodeo documentation (https://Marina.Rodeo.org/).

.SH FILES
.PD 0
.I /etc/Marina.Rodeo/Marina.Rodeo.cfg
.br

.SH AUTHORS

see 
.B /usr/share/doc/Marina.Rodeo/AUTHORS

.SH SEE ALSO
.BR Marina.Rodeo(8)
.PP
Full documentation on Marina.Rodeo is available at
.I https://Marina.Rodeo.org/.
.PP
Mailing lists:
.nf 
users@lists.Marina.Rodeo.org - Marina.Rodeo user community
.nf 
devel@lists.Marina.Rodeo.org - Marina.Rodeo development, new features and unstable version

