.TH Marina.Rodeo-m4cfg 8 17.07.2018 Marina.Rodeo-m4cfg "Marina.Rodeo" 
.\" Process with
.\" groff -man -Tascii Marina.Rodeo-m4cfg.8 
.\"
.SH NAME
Marina.Rodeo-m4cfg \- utility used by systemd to create the
Marina.Rodeo configuration file based on the Marina.Rodeo.m4 file.

.SH SYNOPSIS
.B Marina.Rodeo-m4cfg

.SH DESCRIPTION
.B Marina.Rodeo-m4cfg
is a tool used by system to generate the
.B Marina.Rodeo.cfg
configuration file from the
.B Marina.Rodeo.m4 m4 template

.SH AUTHORS

see 
.B /usr/share/doc/Marina.Rodeo/AUTHORS
.PP
This manual page was written by Razvan Crainea <razvan@Marina.Rodeo.org>
based on osipsconsole manpage by Alejandro Rios P. <alerios@debian.org>,
for the Debian project (and may be used by others).

.SH SEE ALSO
.BR Marina.Rodeo(8), Marina.Rodeo.cfg(5)
.PP
Full documentation on Marina.Rodeo is available at
.I https://Marina.Rodeo.org/.
.PP
Mailing lists:
.nf 
users@lists.Marina.Rodeo.org - Marina.Rodeo user community
.nf 
devel@lists.Marina.Rodeo.org - Marina.Rodeo development, new features and unstable version
