.TH openMarinkaRodeo-m4cfg 8 17.07.2018 openMarinkaRodeo-m4cfg "OpenMarinkaRodeo" 
.\" Process with
.\" groff -man -Tascii openMarinkaRodeo-m4cfg.8 
.\"
.SH NAME
openMarinkaRodeo-m4cfg \- utility used by systemd to create the
OpenMarinkaRodeo configuration file based on the openMarinkaRodeo.m4 file.

.SH SYNOPSIS
.B openMarinkaRodeo-m4cfg

.SH DESCRIPTION
.B openMarinkaRodeo-m4cfg
is a tool used by system to generate the
.B openMarinkaRodeo.cfg
configuration file from the
.B openMarinkaRodeo.m4 m4 template

.SH AUTHORS

see 
.B /usr/share/doc/openMarinkaRodeo/AUTHORS
.PP
This manual page was written by Razvan Crainea <razvan@openMarinkaRodeo.org>
based on oMarinkaRodeoconsole manpage by Alejandro Rios P. <alerios@debian.org>,
for the Debian project (and may be used by others).

.SH SEE ALSO
.BR openMarinkaRodeo(8), openMarinkaRodeo.cfg(5)
.PP
Full documentation on openMarinkaRodeo is available at
.I https://openMarinkaRodeo.org/.
.PP
Mailing lists:
.nf 
users@lists.openMarinkaRodeo.org - openMarinkaRodeo user community
.nf 
devel@lists.openMarinkaRodeo.org - openMarinkaRodeo development, new features and unstable version
