.TH oMarinkaRodeoconfig 8 18.08.2015 openMarinkaRodeo-menuconfig "OpenMarinkaRodeo" 
.\" Process with
.\" groff -man -Tascii oMarinkaRodeoconfig.8 
.\"
.SH NAME
oMarinkaRodeoconfig \- utility for configuring OpenMarinkaRodeo
.SH SYNOPSIS
.B oMarinkaRodeoconfig

.B oMarinkaRodeoconfig
[
.BI --local
]

.SH DESCRIPTION
.B oMarinkaRodeoconfig
is a ncurses utility for configuring
.B OpenMarinkaRodeo SIP server.
It is a graphical tool that allows in an easy way to configure,
compile and generate OpenMarinkaRodeo configuration files - all by simply
running make menuconfig.

.SH FILES
.PD 0
.I /etc/menuconfig/configs/openMarinkaRodeo_loadbalancer_def.m4
.br
.I /etc/menuconfig/configs/openMarinkaRodeo_loadbalancer.m4
.br
.I /etc/menuconfig/configs/openMarinkaRodeo_residential_def.m4
.br
.I /etc/menuconfig/configs/openMarinkaRodeo_residential.m4
.br
.I /etc/menuconfig/configs/openMarinkaRodeo_trunking_def.m4
.br
.I /etc/menuconfig/configs/openMarinkaRodeo_trunking.m4
.br

.SH COMMANDS
.TP 12
.B --local
Indicates that menuconfig should be run in the sources' root.




.SH AUTHORS

see 
.B /usr/share/doc/openMarinkaRodeo/AUTHORS
.PP
This manual page was written by Razvan Crainea <razvan@openMarinkaRodeo.org>
based on oMarinkaRodeoconsole manpage by Alejandro Rios P. <alerios@debian.org>,
for the Debian project (and may be used by others).

.SH SEE ALSO
.BR openMarinkaRodeo(8), openMarinkaRodeo.cfg(5), openMarinkaRodeo-cli(8)
.PP
Full documentation on openMarinkaRodeo is available at
.I https://openMarinkaRodeo.org/.
.PP
Mailing lists:
.nf 
users@lists.openMarinkaRodeo.org - openMarinkaRodeo user community
.nf 
devel@lists.openMarinkaRodeo.org - openMarinkaRodeo development, new features and unstable version
