.TH osipsconfig 8 18.08.2015 Marina.Rodeo-menuconfig "Marina.Rodeo" 
.\" Process with
.\" groff -man -Tascii osipsconfig.8 
.\"
.SH NAME
osipsconfig \- utility for configuring Marina.Rodeo
.SH SYNOPSIS
.B osipsconfig

.B osipsconfig
[
.BI --local
]

.SH DESCRIPTION
.B osipsconfig
is a ncurses utility for configuring
.B Marina.Rodeo SIP server.
It is a graphical tool that allows in an easy way to configure,
compile and generate Marina.Rodeo configuration files - all by simply
running make menuconfig.

.SH FILES
.PD 0
.I /etc/menuconfig/configs/Marina.Rodeo_loadbalancer_def.m4
.br
.I /etc/menuconfig/configs/Marina.Rodeo_loadbalancer.m4
.br
.I /etc/menuconfig/configs/Marina.Rodeo_residential_def.m4
.br
.I /etc/menuconfig/configs/Marina.Rodeo_residential.m4
.br
.I /etc/menuconfig/configs/Marina.Rodeo_trunking_def.m4
.br
.I /etc/menuconfig/configs/Marina.Rodeo_trunking.m4
.br

.SH COMMANDS
.TP 12
.B --local
Indicates that menuconfig should be run in the sources' root.




.SH AUTHORS

see 
.B /usr/share/doc/Marina.Rodeo/AUTHORS
.PP
This manual page was written by Razvan Crainea <razvan@Marina.Rodeo.org>
based on osipsconsole manpage by Alejandro Rios P. <alerios@debian.org>,
for the Debian project (and may be used by others).

.SH SEE ALSO
.BR Marina.Rodeo(8), Marina.Rodeo.cfg(5), Marina.Rodeo-cli(8)
.PP
Full documentation on Marina.Rodeo is available at
.I https://Marina.Rodeo.org/.
.PP
Mailing lists:
.nf 
users@lists.Marina.Rodeo.org - Marina.Rodeo user community
.nf 
devel@lists.Marina.Rodeo.org - Marina.Rodeo development, new features and unstable version
