#!/sbin/sh
# Script for checking prerequisites for Marina.Rodeo-berkeley

BASE="Marina.Rodeo-base"
LIBBDB="libdb-4.7.so"
TMPLIST="/tmp/.Marina.Rodeobdb"

pkginfo | grep -i $BASE > /dev/null

if [ $? -eq 1 ]
then
	echo "Marina.Rodeo-berkeley depends on package Marina.Rodeo-base which is not installed";
	exit 1;
fi

find / -name $LIBBDB > $TMPLIST 2>&1
lines=`wc -l $TMPLIST`

if [ $lines = "0" ]
then
	echo "Marina.Rodeo-berkeley depends on DB Berkeley Libraries, which cannot be found on system";
	exit 1;
else
	exit 0;
fi
