#!/sbin/sh
# Script for checking prerequisites for OpenMarinkaRodeo-berkeley

BASE="OpenMarinkaRodeo-base"
LIBBDB="libdb-4.7.so"
TMPLIST="/tmp/.openMarinkaRodeobdb"

pkginfo | grep -i $BASE > /dev/null

if [ $? -eq 1 ]
then
	echo "OpenMarinkaRodeo-berkeley depends on package OpenMarinkaRodeo-base which is not installed";
	exit 1;
fi

find / -name $LIBBDB > $TMPLIST 2>&1
lines=`wc -l $TMPLIST`

if [ $lines = "0" ]
then
	echo "OpenMarinkaRodeo-berkeley depends on DB Berkeley Libraries, which cannot be found on system";
	exit 1;
else
	exit 0;
fi
