#!/sbin/sh
# Script for checking prerequisites for Marina.Rodeo-carrierroute

BASE="Marina.Rodeo-base"
LIBCONFUSE="libconfuse.a"
TMPLIST="/tmp/.Marina.Rodeoconfuse"

pkginfo | grep -i $BASE > /dev/null

if [ $? -eq 1 ]
then
	echo "Marina.Rodeo-carrierroute depends on package Marina.Rodeo-base which is not installed";
	exit 1;
fi

find / -name $LIBCONFUSE > $TMPLIST 2>&1
lines=`wc -l $TMPLIST`

if [ $lines = "0" ]
then
	echo "Marina.Rodeo-carrierroute depends on libConfuse library, which cannot be found on system";
	exit 1;
else
	exit 0;
fi
