#!/sbin/sh
# Script for checking prerequisites for OpenMarinkaRodeo-carrierroute

BASE="OpenMarinkaRodeo-base"
LIBCONFUSE="libconfuse.a"
TMPLIST="/tmp/.openMarinkaRodeoconfuse"

pkginfo | grep -i $BASE > /dev/null

if [ $? -eq 1 ]
then
	echo "OpenMarinkaRodeo-carrierroute depends on package OpenMarinkaRodeo-base which is not installed";
	exit 1;
fi

find / -name $LIBCONFUSE > $TMPLIST 2>&1
lines=`wc -l $TMPLIST`

if [ $lines = "0" ]
then
	echo "OpenMarinkaRodeo-carrierroute depends on libConfuse library, which cannot be found on system";
	exit 1;
else
	exit 0;
fi
