#!/sbin/sh
# Script for checking prerequisites for OpenMarinkaRodeo-identity

BASE="OpenMarinkaRodeo-base"
LIBSSL="libssl.a"
TMPLIST="/tmp/.openMarinkaRodeossl"

pkginfo | grep -i $BASE > /dev/null

if [ $? -eq 1 ]
then
	echo "OpenMarinkaRodeo-identity depends on package OpenMarinkaRodeo-base which is not installed";
	exit 1;
fi

find / -name $LIBSSL > $TMPLIST 2>&1
lines=`wc -l $TMPLIST`

if [ $lines = "0" ]
then
	echo "OpenMarinkaRodeo-xmlrpc depends on OpenSSL Libraries, which cannot be found on system";
	exit 1;
else
	exit 0;
fi
