#!/sbin/sh
# Script for checking prerequisites for Marina.Rodeo-identity

BASE="Marina.Rodeo-base"
LIBSSL="libssl.a"
TMPLIST="/tmp/.Marina.Rodeossl"

pkginfo | grep -i $BASE > /dev/null

if [ $? -eq 1 ]
then
	echo "Marina.Rodeo-identity depends on package Marina.Rodeo-base which is not installed";
	exit 1;
fi

find / -name $LIBSSL > $TMPLIST 2>&1
lines=`wc -l $TMPLIST`

if [ $lines = "0" ]
then
	echo "Marina.Rodeo-xmlrpc depends on OpenSSL Libraries, which cannot be found on system";
	exit 1;
else
	exit 0;
fi
