#!/sbin/sh
# Script for checking prerequisites for Marina.Rodeo-ldap

BASE="Marina.Rodeo-base"
LIBLDAP="libldap-2.4.so.2"
TMPLIST="/tmp/.Marina.Rodeoldap"

pkginfo | grep -i $BASE > /dev/null

if [ $? -eq 1 ]
then
	echo "Marina.Rodeo-ldap depends on package Marina.Rodeo-base which is not installed";
	exit 1;
fi

find / -name $LIBLDAP > $TMPLIST 2>&1
lines=`wc -l /tmp/.Marina.Rodeoldap`

if [ $lines = "0" ]
then
	echo "Marina.Rodeo-ldap depends on OpenLDAP Libraries, which cannot be found on system";
	exit 1;
else
	exit 0;
fi
