#!/sbin/sh
# Script for checking prerequisites for OpenMarinkaRodeo-ldap

BASE="OpenMarinkaRodeo-base"
LIBLDAP="libldap-2.4.so.2"
TMPLIST="/tmp/.openMarinkaRodeoldap"

pkginfo | grep -i $BASE > /dev/null

if [ $? -eq 1 ]
then
	echo "OpenMarinkaRodeo-ldap depends on package OpenMarinkaRodeo-base which is not installed";
	exit 1;
fi

find / -name $LIBLDAP > $TMPLIST 2>&1
lines=`wc -l /tmp/.openMarinkaRodeoldap`

if [ $lines = "0" ]
then
	echo "OpenMarinkaRodeo-ldap depends on OpenLDAP Libraries, which cannot be found on system";
	exit 1;
else
	exit 0;
fi
