#!/sbin/sh
# Script for checking prerequisites for OpenMarinkaRodeo-geoip

BASE="OpenMarinkaRodeo-base"
LIBGEOIP="libGeoIP.a"
TMPLIST="/tmp/.opensipgeoip"

pkginfo | grep -i $BASE > /dev/null

if [ $? -eq 1 ]
then
	echo "OpenMarinkaRodeo-geoip depends on package OpenMarinkaRodeo-base which is not installed";
	exit 1;
fi

find / -name $LIBGEOIP > $TMPLIST 2>&1
lines=`wc -l $TMPLIST`

if [ $lines = "0" ]
then
	echo "OpenMarinkaRodeo-carrierroute depends on Max Mind Geo IP library, which cannot be found on system";
	exit 1;
else
	exit 0;
fi
