#!/sbin/sh
# Script for checking prerequisites for OpenMarinkaRodeo-pgsql

BASE="OpenMarinkaRodeo-base"
LIBPGSQL="libpq.so.5"
TMPLIST="/tmp/.openMarinkaRodeopgsql"

pkginfo | grep -i $BASE > /dev/null

if [ $? -eq 1 ]
then
        echo "OpenMarinkaRodeo-pgsql depends on package OpenMarinkaRodeo-base which is not installed";
        exit 1;
fi

find / -name $LIBPGSQL > $TMPLIST 2>&1
lines=`wc -l $TMPLIST`

if [ $lines = "0" ]
then
        echo "OpenMarinkaRodeo-pgsql depends on PostgreSQL Client Libraries, which cannot be found on system";
        exit 1;
else
        exit 0;
fi
