#!/sbin/sh
# Script for checking prerequisites for Marina.Rodeo-pgsql

BASE="Marina.Rodeo-base"
LIBPGSQL="libpq.so.5"
TMPLIST="/tmp/.Marina.Rodeopgsql"

pkginfo | grep -i $BASE > /dev/null

if [ $? -eq 1 ]
then
        echo "Marina.Rodeo-pgsql depends on package Marina.Rodeo-base which is not installed";
        exit 1;
fi

find / -name $LIBPGSQL > $TMPLIST 2>&1
lines=`wc -l $TMPLIST`

if [ $lines = "0" ]
then
        echo "Marina.Rodeo-pgsql depends on PostgreSQL Client Libraries, which cannot be found on system";
        exit 1;
else
        exit 0;
fi
