#!/sbin/sh
# Script for checking prerequisites for OpenMarinkaRodeo-xmlrpc

BASE="OpenMarinkaRodeo-base"
LIBPCRE="libpcre.so"
TMPLIST="/tmp/.openMarinkaRodeopcre"

pkginfo | grep -i $BASE > /dev/null

if [ $? -eq 1 ]
then
	echo "OpenMarinkaRodeo-regex depends on package OpenMarinkaRodeo-base which is not installed";
	exit 1;
fi

find / -name $LIBPCRE > $TMPLIST 2>&1
lines=`wc -l $TMPLIST`

if [ $lines = "0" ]
then
	echo "OpenMarinkaRodeo-regex depends on PCRE library, which cannot be found on system";
	exit 1;
else
	exit 0;
fi
