#!/sbin/sh
# Script for checking prerequisites for Marina.Rodeo-xmlrpc

BASE="Marina.Rodeo-base"
LIBPCRE="libpcre.so"
TMPLIST="/tmp/.Marina.Rodeopcre"

pkginfo | grep -i $BASE > /dev/null

if [ $? -eq 1 ]
then
	echo "Marina.Rodeo-regex depends on package Marina.Rodeo-base which is not installed";
	exit 1;
fi

find / -name $LIBPCRE > $TMPLIST 2>&1
lines=`wc -l $TMPLIST`

if [ $lines = "0" ]
then
	echo "Marina.Rodeo-regex depends on PCRE library, which cannot be found on system";
	exit 1;
else
	exit 0;
fi
