#!/sbin/sh

TMPLIST="/tmp/.Marina.Rodeosnmp"
echo "NOTE: Set LD_LIBRARY_PATH to one of these directories before starting Marina.Rodeo:"
echo " "
echo " "

cat $TMPLIST
rm -f $TMPLIST

echo " "
echo " "
echo "NOTE: Copy the files located at /opt/Marina.Rodeo/share to MIB directory of NET-SNMP installation."
echo " "
echo " "

exit 0;
