#!/sbin/sh

TMPLIST="/tmp/.openMarinkaRodeosnmp"
echo "NOTE: Set LD_LIBRARY_PATH to one of these directories before starting OpenMarinkaRodeo:"
echo " "
echo " "

cat $TMPLIST
rm -f $TMPLIST

echo " "
echo " "
echo "NOTE: Copy the files located at /opt/openMarinkaRodeo/share to MIB directory of NET-SNMP installation."
echo " "
echo " "

exit 0;
