#!/sbin/sh
# Script for checking prerequisites for OpenMarinkaRodeo-xmlrpc

BASE="OpenMarinkaRodeo-base"
LIBXMLRPC="libxmlrpc.so.3"
TMPLIST="/tmp/.openMarinkaRodeoxmlrpc"

pkginfo | grep -i $BASE > /dev/null

if [ $? -eq 1 ]
then
	echo "OpenMarinkaRodeo-xmlrpc depends on package OpenMarinkaRodeo-base which is not installed";
	exit 1;
fi

find / -name $LIBXMLRPC > $TMPLIST 2>&1
lines=`wc -l $TMPLIST`

if [ $lines = "0" ]
then
	echo "OpenMarinkaRodeo-xmlrpc depends on MySQL Client Libraries, which cannot be found on system";
	exit 1;
else
	exit 0;
fi
