post_install() {
	echo "OpenMarinkaRodeo suite is build as a modular system."
	echo "This packages "openMarinkaRodeo" just includes the core functionality and the parser."
	echo "All sophisticated SIP packet handling is provided through dedicated modules and usage will vary,"
	echo "Please install "openMarinkaRodeo-modules" and adapt the configuration to your individual needs."
	echo "The documentation is provided via the "openMarinkaRodeo-documentation" package in different formats."
	echo "Beside html-, and text files you will find example configurations explaining the integration of available modules." 
	echo ""
	echo "You are encouraged to make use of a database module."
	echo "Thus you needed to install the relevant database package in combination with the corresponding"
	echo "openMarinkaRodeo module package:
	echo "1) 'pacman -S openMarinkaRodeo-modules'"
	echo "2) To create the openMarinkaRodeo specific tables make use of 'openMarinkaRodeodbctl create'"
	echo "   eg for MySQL:      'pacman -S mariadb mariadb-clients' -> 'openMarinkaRodeodbctl create'"
	echo "   eg for PostgreSQL: 'pacman -S postgresql postgresql-client' -> 'openMarinkaRodeodbctl create'"

	useradd --system --group \
		--shell /bin/false --comment "OpenMarinkaRodeo" \
		--home-dir $HOMEDIR --no-create-home openMarinkaRodeo || true
}
